Uwsgi
brianmaissy/Yaamod pull request #2
Opened 2019-10-20 11:18 UTC by oneYAD

2019-10-20 11:20 UTC, brianmaissy requested changes

2019-10-20 11:20 UTC, brianmaissy commented on django/yaamod/wsgi.py
> +        sys.path.append(path)
too much whitespace.
also it should be yaamod, not VG (it should be changed on the production server too)

2019-11-15 08:25 UTC, brianmaissy requested changes

2019-11-15 08:25 UTC, brianmaissy commented on django/yaamod/settings.py
> +ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'www.yaamod.co.il']
allow without www

2019-11-15 08:36 UTC, oneYAD commented
fix pull request review

2019-11-15 09:57 UTC, brianmaissy approved these changes

2019-11-15 09:59 UTC, merged